### ISSUE TITLE
Any updates expected?

### ISSUE THREAD

**Issue by tersekmatija** [openvinotoolkit/npu_compiler#8]
Hey @Maxim-Doronin @vpux-compiler-owners,

Are there any updates expected in this repo?

**Comment by kirill-korniakov** [comment]
Probably... https://github.com/openvinotoolkit/vpux-plugin/pull/10

**Comment by Maxim-Doronin** [comment]
Yes, we are going to publish the latest release of VPUX plugin and compiler soon. Kirill is right, you can follow https://github.com/openvinotoolkit/vpux-plugin/pull/10
